version: '3.3'

services:
  firefly_iii_core:
    image: fireflyiii/core:latest
    hostname: firefly
    container_name: firefly_iii_core
    restart: always
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload

volumes:
  firefly_iii_upload:
